
TestEngine.setTestSuiteName("[Filesystem]", 5*1000);
TestEngine.addTest(true, UTC_filesystem_resolve_location_P_001,             			"UTC_filesystem_resolve_location_P_001");
TestEngine.addTest(true, UTC_filesystem_resolve_mode_P_002,             				"UTC_filesystem_resolve_mode_P_002");
TestEngine.addTest(true, UTC_filesystem_getstorage_label_P_001,             			"UTC_filesystem_getstorage_label_P_001");
TestEngine.addTest(true, UTC_filesystem_iststorage_P_001,             					"UTC_filesystem_iststorage_P_001");
TestEngine.addTest(true, UTC_filesystem_removestoragestaechangelistener_P_001,          "UTC_filesystem_removestoragestaechangelistener_P_001");
TestEngine.addTest(true, UTC_filesystem_listfiles_P_001,             					"UTC_filesystem_listfiles_P_001");
TestEngine.addTest(true, UTC_filesystem_file_to_uri_P_001,             					"UTC_filesystem_file_to_uri_P_001");
TestEngine.addTest(true, UTC_filesystem_file_listFiles_P_001,             				"UTC_filesystem_file_listFiles_P_001");
TestEngine.addTest(true, UTC_filesystem_file_listFiles_P_002, 							"UTC_filesystem_file_listFiles_P_002");
TestEngine.addTest(true, UTC_filesystem_file_openStream_P_001, 							"UTC_filesystem_file_openStream_P_001");
TestEngine.addTest(true, UTC_filesystem_file_openStream_P_002, 							"UTC_filesystem_file_openStream_P_002");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_P_001, 							"UTC_filesystem_file_readAsText_P_001");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_P_002, 							"UTC_filesystem_file_readAsText_P_002");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_P_001, 								"UTC_filesystem_file_copyTo_P_001");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_P_003, 								"UTC_filesystem_file_copyTo_P_003");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_P_001, 								"UTC_filesystem_file_moveTo_P_001");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_P_003, 								"UTC_filesystem_file_moveTo_P_003");
TestEngine.addTest(true, UTC_filesystem_file_createFile_P_001, 							"UTC_filesystem_file_createFile_P_001");
TestEngine.addTest(true, UTC_filesystem_file_createDirectory_P_001, 					"UTC_filesystem_file_createDirectory_P_001");
TestEngine.addTest(true, UTC_filesystem_file_resolve_P_001, 							"UTC_filesystem_file_resolve_P_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_P_001, 					"UTC_filesystem_file_deleteDirectory_P_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_P_002,  					"UTC_filesystem_file_deleteDirectory_P_002");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_P_001, 							"UTC_filesystem_file_deleteFile_P_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_P_002,   						"UTC_filesystem_file_deleteFile_P_002");
TestEngine.addTest(true, UTC_filesystem_file_write_read_close_P_001, 					"UTC_filesystem_file_write_read_close_P_001");
TestEngine.addTest(true, UTC_filesystem_file_write_readBytes_P_001, 					"UTC_filesystem_file_write_readBytes_P_001");
TestEngine.addTest(true, UTC_filesystem_file_write_readBase64_P_001, 					"UTC_filesystem_file_write_readBase64_P_001");
TestEngine.addTest(true, UTC_filesystem_resolve_invalid_pram_success_callback_N_001, 						"UTC_filesystem_resolve_invalid_pram_success_callback_N_001");
TestEngine.addTest(true, UTC_filesystem_resolve_invalid_pram_error_callback_N_002,   						"UTC_filesystem_resolve_invalid_pram_error_callback_N_002");
TestEngine.addTest(true, UTC_filesystem_resolve_invalid_pram_location_N_003,         						"UTC_filesystem_resolve_invalid_pram_location_N_003");
TestEngine.addTest(true, UTC_filesystem_resolve_invalid_pram_mode_N_004,             						"UTC_filesystem_resolve_invalid_pram_mode_N_004");
TestEngine.addTest(true, UTC_filesystem_getstorage_invalid_pram_onsuccess_N_001,     						"UTC_filesystem_getstorage_invalid_pram_onsuccess_N_001");
TestEngine.addTest(true, UTC_filesystem_getstorage_invalid_pram_onerror_N_002,      						"UTC_filesystem_getstorage_invalid_pram_onerror_N_002");
TestEngine.addTest(true, UTC_filesystem_getstorage_invalid_pram_label_N_003,         						"UTC_filesystem_getstorage_invalid_pram_label_N_003");
TestEngine.addTest(true, UTC_filesystem_liststorages_invalid_pram_onsuccess_N_001,   						"UTC_filesystem_liststorages_invalid_pram_onsuccess_N_001");
TestEngine.addTest(true, UTC_filesystem_liststorages_invalid_pram_onerror_N_002,     						"UTC_filesystem_liststorages_invalid_pram_onerror_N_002");
TestEngine.addTest(true, UTC_filesystem_addstoragestatechangelistener_invalid_pram_onsuccess_N_001,  		"UTC_filesystem_addstoragestatechangelistener_invalid_pram_onsuccess_N_001");
TestEngine.addTest(true, UTC_filesystem_addstoragestatechangelistener_invalid_pram_onerror_N_002,   	 	"UTC_filesystem_addstoragestatechangelistener_invalid_pram_onerror_N_002");
TestEngine.addTest(true, UTC_filesystem_listfiles_invalid_pram_onsuccess_N_001,      						"UTC_filesystem_listfiles_invalid_pram_onsuccess_N_001");
TestEngine.addTest(true, UTC_filesystem_listfiles_invalid_pram_onerror_N_002,        						"UTC_filesystem_listfiles_invalid_pram_onerror_N_002");
TestEngine.addTest(true, UTC_filesystem_file_openStream_error_successcb_invalid_param_N_001,     			"UTC_filesystem_file_openStream_error_successcb_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_openStream_error_mode_invalid_param_N_002,     				"UTC_filesystem_file_openStream_error_mode_invalid_param_N_002");
TestEngine.addTest(true, UTC_filesystem_file_openStream_error_encoding_invalid_param_N_003,     			"UTC_filesystem_file_openStream_error_encoding_invalid_param_N_003");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_error_successcb_invalid_param_N_001,     			"UTC_filesystem_file_readAsText_error_successcb_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_error_errorcb_invalid_param_N_002,     				"UTC_filesystem_file_readAsText_error_errorcb_invalid_param_N_002");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_error_encoding_invalid_param_N_003,     			"UTC_filesystem_file_readAsText_error_encoding_invalid_param_N_003");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_error_successcb_invalid_param_N_001,     				"UTC_filesystem_file_copyTo_error_successcb_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_error_errorcb_invalid_param_N_002,     					"UTC_filesystem_file_copyTo_error_errorcb_invalid_param_N_002");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_error_filepath_invalid_param_N_003,     				"UTC_filesystem_file_copyTo_error_filepath_invalid_param_N_003");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_error_destination_invalid_param_N_004,    				"UTC_filesystem_file_copyTo_error_destination_invalid_param_N_004");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_error_successcb_invalid_param_N_001,     				"UTC_filesystem_file_moveTo_error_successcb_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_error_errorcb_invalid_param_N_002,     					"UTC_filesystem_file_moveTo_error_errorcb_invalid_param_N_002");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_error_originfile_invalid_param_N_003,     				"UTC_filesystem_file_moveTo_error_originfile_invalid_param_N_003");
TestEngine.addTest(true, UTC_filesystem_file_resolve_error_dir_invalid_param_N_001,     					"UTC_filesystem_file_resolve_error_dir_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_error_successcb_invalid_param_N_001,    		"UTC_filesystem_file_deleteDirectory_error_successcb_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_error_errorcb_invalid_param_N_002,     		"UTC_filesystem_file_deleteDirectory_error_errorcb_invalid_param_N_002");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_error_dir_invalid_param_N_003,     			"UTC_filesystem_file_deleteDirectory_error_dir_invalid_param_N_003");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_error_successcb_invalid_param_N_001,     			"UTC_filesystem_file_deleteFile_error_successcb_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_error_errorcb_invalid_param_N_002,     				"UTC_filesystem_file_deleteFile_error_errorcb_invalid_param_N_002");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_error_dir_invalid_param_N_003,     					"UTC_filesystem_file_deleteFile_error_dir_invalid_param_N_003");
TestEngine.addTest(true, UTC_filesystem_file_read_error_count_invalid_param_N_001,     						"UTC_filesystem_file_read_error_count_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_readBytes_error_invalid_param_N_001,     						"UTC_filesystem_file_readBytes_error_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_file_writeBytes_error_octect_invalid_param_N_001,     				"UTC_filesystem_file_writeBytes_error_octect_invalid_param_N_001");
TestEngine.addTest(true, UTC_filesystem_remove_listener_invalid_param_N_001,     							"UTC_filesystem_remove_listener_invalid_param_N_001");
// test with file:///tmp location
TestEngine.addTest(true, UTC_filesystem_change_test_root_location, 							"UTC_filesystem_change_test_root_location");
TestEngine.addTest(true, UTC_filesystem_shift_jis, 									"UTC_filesystem_shft_jis");
TestEngine.addTest(true, UTC_filesystem_resolve_location_P_001,             			"UTC_filesystem_resolve_location_P_001");
TestEngine.addTest(true, UTC_filesystem_resolve_mode_P_002,             				"UTC_filesystem_resolve_mode_P_002");
TestEngine.addTest(true, UTC_filesystem_getstorage_label_P_001,             			"UTC_filesystem_getstorage_label_P_001");
TestEngine.addTest(true, UTC_filesystem_iststorage_P_001,             					"UTC_filesystem_iststorage_P_001");
TestEngine.addTest(true, UTC_filesystem_removestoragestaechangelistener_P_001,          "UTC_filesystem_removestoragestaechangelistener_P_001");
TestEngine.addTest(true, UTC_filesystem_file_to_uri_P_001,             					"UTC_filesystem_file_to_uri_P_001");
TestEngine.addTest(true, UTC_filesystem_file_openStream_P_001, 							"UTC_filesystem_file_openStream_P_001");
TestEngine.addTest(true, UTC_filesystem_file_openStream_P_002, 							"UTC_filesystem_file_openStream_P_002");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_P_001, 							"UTC_filesystem_file_readAsText_P_001");
TestEngine.addTest(true, UTC_filesystem_file_readAsText_P_002, 							"UTC_filesystem_file_readAsText_P_002");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_P_001, 								"UTC_filesystem_file_copyTo_P_001");
TestEngine.addTest(true, UTC_filesystem_file_copyTo_P_003, 								"UTC_filesystem_file_copyTo_P_003");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_P_001, 								"UTC_filesystem_file_moveTo_P_001");
TestEngine.addTest(true, UTC_filesystem_file_moveTo_P_003, 								"UTC_filesystem_file_moveTo_P_003");
TestEngine.addTest(true, UTC_filesystem_file_createFile_P_001, 							"UTC_filesystem_file_createFile_P_001");
TestEngine.addTest(true, UTC_filesystem_file_createDirectory_P_001, 					"UTC_filesystem_file_createDirectory_P_001");
TestEngine.addTest(true, UTC_filesystem_file_resolve_P_001, 							"UTC_filesystem_file_resolve_P_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_P_001, 					"UTC_filesystem_file_deleteDirectory_P_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteDirectory_P_002,  					"UTC_filesystem_file_deleteDirectory_P_002");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_P_001, 							"UTC_filesystem_file_deleteFile_P_001");
TestEngine.addTest(true, UTC_filesystem_file_deleteFile_P_002,   						"UTC_filesystem_file_deleteFile_P_002");
TestEngine.addTest(true, UTC_filesystem_file_write_read_close_P_001, 					"UTC_filesystem_file_write_read_close_P_001");
TestEngine.addTest(true, UTC_filesystem_file_write_readBytes_P_001, 					"UTC_filesystem_file_write_readBytes_P_001");
TestEngine.addTest(true, UTC_filesystem_file_write_readBase64_P_001, 					"UTC_filesystem_file_write_readBase64_P_001"); 
TestEngine.addTest(true, UTC_filesystem_check_invalid_mode,
	"UTC_filesystem_check_invalid_mode"); 
TestEngine.addTest(true, UTC_filesystem_invoke_write_permission_api_with_FileOjbect_resolved_as_r,
	"UTC_filesystem_invoke_write_permission_api_with_FileOjbect_resolved_as_r"); 
TestEngine.addTest(true, UTC_filesystem_check_sdcard_resolve,
	"UTC_filesystem_check_sdcard_resolve"); 
//TestEngine.addTest(true, UTC_filesystem_stupid_resolve_delete,
//	"UTC_filesystem_stupid_resolve_delete");
TestEngine.addTest(true, UTC_filesystem_copyTo_moveTo_error,
	"UTC_filesystem_copyTo_moveTo_error");
// should be manual test
//TestEngine.addTest(true, UTC_filesystem_permission_denied_error,
	//"UTC_filesystem_permission_denied_error");
